### ISSUE TITLE
Wikimedia GitLab code repository and GitHub code repository out of sync

### ISSUE THREAD

**Issue by aklapper** [WikiMovimentoBrasil/povoconta#2]
https://gitlab.wikimedia.org/toolforge-repos/povoconta/-/commits/master?ref_type=heads exists, however it seems to be out of sync with newer https://github.com/WikiMovimentoBrasil/povoconta/commits/master (which has one commit more).

It would be great if you could clarify, visibly for anyone finding one of these two repositories, where to find the most recent codebase, or set up syncing/mirroring between these two places. Thanks.

**Comment by Ederporto** [comment]
I have absolutely no memory of creating the gitlab repository. Are you sure it was me? I don't have access to gitlab.wikimedia.org, apparently. I always try to put this information in the admin.toolforge.org tool profile, for this tool is marking github.

**Comment by Ederporto** [comment]
@aklapper I have absolutely no memory of creating the gitlab repository. Are you sure it was me? I don't have access to gitlab.wikimedia.org, apparently. I always try to put this information in the admin.toolforge.org tool profile, for this tool is marking github.

**Comment by aklapper** [comment]
Thanks a lot for the clarification! I don't know the history here either; I'll try to find out how to potentially delete the Wikimedia GitLab repo so it's clearer for anyone to find the latest code. (Big thanks for the toolinfo.json data!)

**Comment by bd808** [comment]
> @aklapper I have absolutely no memory of creating the gitlab repository. Are you sure it was me?

```
striker_admin@m5-master.eqiad.wmnet(striker)> select * from tools_gitlabrepo where name = 'povoconta'\G
*************************** 1. row ***************************
           id: 216
         tool: povoconta
         name: povoconta
      repo_id: 673
 created_date: 2022-09-07 22:23:14.371532
created_by_id: 112
1 row in set (0.002 sec)

striker_admin@m5-master.eqiad.wmnet(striker)> select ldapname, shellname, sulname from labsauth_labsuser where id=112;
+-----------+-----------+-----------+
| ldapname  | shellname | sulname   |
+-----------+-----------+-----------+
| Ederporto | ederporto | Ederporto |
+-----------+-----------+-----------+
1 row in set (0.001 sec)
```

You used https://toolsadmin.wikimedia.org to create a Diffusion repository hosted by https://phabricator.wikimedia.org on 2022-09-07. That Diffusion repo was then migrated to https://gitlab.wikimedia.org as part of https://phabricator.wikimedia.org/T315706.
